apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-ol-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/ollama
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-ol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 10Gi


