apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    pod-security.kubernetes.io/enforce: restricted

---

apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
  labels:
    pod-security.kubernetes.io/enforce: restricted

---

apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted